### PR TITLE
Run function on mouse and human datasets currently

### PR DESCRIPTION
**Pull request by SidhantPuntambekar**
Run appendGenes on all current human and mouse datasets to create atlas. Should solve #14

### CODE REVIEW

**Comment by SidhantPuntambekar** [comment]
@kriemo @raysinensis I have committed new versions of the mouse and human atlas to this PR.

**Comment by SidhantPuntambekar** [comment]
@kriemo @raysinensis Column names have been updated for both atlases. Will merge this pr if you approve.

**Comment by kriemo** [comment]
Hi Sid, some suggestions:

https://github.com/rnabioco/scRNA-seq-Cell-Reference-Matrix/blob/3a756bad386b9a6d20c2dd5ee454460f5dd49b20/R/homoSapiens/humanAtlas.r#L3
Not sure if you need the [`patchwork`](https://github.com/thomasp85/patchwork) package  for this script. 

https://github.com/rnabioco/scRNA-seq-Cell-Reference-Matrix/blob/3a756bad386b9a6d20c2dd5ee454460f5dd49b20/R/homoSapiens/humanAtlas.r#L9

I would use exact file paths instead of `file.choose`. 

lines 40-56 don't seem necessary anymore now that we are using the appendGenes approach. 


https://github.com/rnabioco/scRNA-seq-Cell-Reference-Matrix/blob/3a756bad386b9a6d20c2dd5ee454460f5dd49b20/R/homoSapiens/humanAtlas.r#L85

lines 85-101 could be simplified using an iteration approach:
```r
mats <- list(
  matrix1,
  matrix2,
  matrix3)

# iterate over list and get new matrices
new_mats <- lapply(mats, function(x){
  as.matrix(x) %>% appendGenes(humanGenesVector = humanGenesVector, GSEMatrix = .)
})

# cbind a list of matrices
humanAtlas <- do.call(cbind, new_mats)

```

**Comment by SidhantPuntambekar** [comment]
@kriemo I have made the following changes to humanAtlas.r


- Removed patchwork library
- Added actual file paths
- Got rid of subsetting common genes
- Iterative approach to simplify creation of humanAtlas

I need to apply the same changes to mouseAtlas.r and then you can approve the changes.

**Comment by SidhantPuntambekar** [comment]
@kriemo All issues have been fixed with respect to mouseAtlas.r and humanAtlas.r

**Pull request merged**
